name = "modded"
author = "Levente"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc01e8d633714255d7282cb26fdad47d3b01020aa401b842b6ed2dbcece035b4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
