name = "modded"
author = "Levente"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1c81fb57f6789cf8f23322b61624d6b7aa4fed6d22aa14f6deb064be9f798f2"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
