name = "modded"
author = "Levente"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8243cfd29b39296c125fb6bb97ab3f5dd5eb3545730d68d6a61ff49b8377d82"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
